### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Castle Stage, part 1: app crashes just after defeating Disc Boss.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#82] opened 2017-11-11 14:23 UTC
Yep, it crashed just like that.  Previously, these games *never* crashed for me.  So the previous crashes reported were also caused by the app (on intro stage), not by external sources, like I thought.

**Comment by ghost** [comment] 2017-11-11 14:43
crashed again after defeating Castle Stage part 2 boss - showed the stage selection menu for a second and crashed..

**Comment by protoman** [comment] 2017-11-14 12:47
Please, provide logcat for the crash so I can get more details.

**Comment by protoman** [comment] 2021-06-19 17:44
Can't reproduce, tthus closing issue.

**Closed as completed by protoman** 2021-06-19 17:44 UTC
Labels: bug
