### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Atlantida Stage: various issues - in screenshots. 

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#38] opened 2017-11-05 14:20 UTC
![screenshot_2017-11-05-14-28-01](https://user-images.githubusercontent.com/33324878/32415616-c72d5474-c23c-11e7-9694-7db69d9ad120.png)
![screenshot_2017-11-05-14-36-08](https://user-images.githubusercontent.com/33324878/32415617-c7667218-c23c-11e7-9e02-dcd3f11671b0.png)
![screenshot_2017-11-05-14-41-44](https://user-images.githubusercontent.com/33324878/32415618-c795a506-c23c-11e7-9897-eaa7bd5e3430.png)
![screenshot_2017-11-05-14-43-46](https://user-images.githubusercontent.com/33324878/32415619-c7ce6a80-c23c-11e7-83d9-075919bda9d7.png)
![screenshot_2017-11-05-14-44-00](https://user-images.githubusercontent.com/33324878/32415620-c7f7e996-c23c-11e7-8350-563e0ef859eb.png)
![screenshot_2017-11-05-14-44-39](https://user-images.githubusercontent.com/33324878/32415621-c83f8b84-c23c-11e7-9923-132f491c1902.png)
![screenshot_2017-11-05-14-48-36](https://user-images.githubusercontent.com/33324878/32415622-c86fdb0e-c23c-11e7-9ebf-cb81afe2dd2f.png)
![screenshot_2017-11-05-14-49-29](https://user-images.githubusercontent.com/33324878/32415623-c899d148-c23c-11e7-8ca8-80378618e8b5.png)

**Comment by protoman** [comment] 2017-11-05 14:30
Ok, those are several different problems, so I will later break those into different issues.
The weapon menu problem was fixed this morning. The are in Atlantida that you can jump high is set as water for me to test, I will change the terrain back to unblocked.
Poweups not falling, or shields falling were already fixed and the cause is the easy or hard mode difficulty blocks and spikes.

**Comment by protoman** [comment] 2021-06-19 16:32
I did most of the fixes, so I am closing this issue, please let me know if you still think it needs fixes.

**Closed as completed by protoman** 2021-06-19 16:32 UTC
Labels: edit, rockbot1
